services:
  json-server:
    build: .
    ports:
      - "8080:8080"   
  trmnlp:
    image: schrockwell/trmnlp
    ports:
      - 4567:4567
    volumes:
      - .:/plugin
    restart: unless-stopped
